name: test-javascript-stryker

on:
  push:
    branches:
      - main
    paths:
      - javascript/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - javascript/**
      - testdata/**
      - .github/**

jobs:
  stryker-javascript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json
    - run: npm install
      working-directory: javascript
    - run: npm run stryker
      working-directory: javascript
    - uses: actions/upload-artifact@v6
      with:
        name: stryker-report
        path: |
          javascript/reports/mutation/html/index.html
          javascript/reports/mutation/mutation.json
